### ISSUE TITLE
enlace

### ISSUE THREAD

**Issue by crguezl** [ULL-ESIT-DMSI-2223/nextjs-guillermo-martin-lorenzo-alu0101128931#1]
Sin enlace en la parte derecha en el about: debe estar apuntando al despliegue

**Comment by crguezl** [comment]
Errores:

<img width="1422" alt="Captura de pantalla 2023-01-15 a las 12 57 05" src="https://user-images.githubusercontent.com/1142554/212542000-f0676a64-1838-42ae-8781-225e96778d10.png">

**Comment by alu0101128931** [comment]
Errores corregidos

**Comment by crguezl** [comment]
Sigue faltando la url de despliegue en **about** del repo

**Comment by alu0101128931** [comment]
Es verdad, perdone, ahora si.

**Comment by crguezl** [comment]
👍
